### ISSUE TITLE
Text output files should use .txt file extension

### ISSUE THREAD

**Issue by stweil** [OCR-D/ocrd_fileformat#11]
Currently the conversion from PAGE XML to text (`"page text"`) creates text files with the file extension `.xml` which is unexpected and can cause problems with viewers which expect XML but get pure text.

**Comment by stweil** [comment]
@kba, how should this issue be addressed? Do we require users to set the correct extension by using the `ext` parameter?

The `ext` parameter default is set in the JSON file. It is currently `.xml`, and I am afraid that automatic setting of the right parameter value would not fit to this default value. What about changing the default to an empty string and using that as an indicator to set the file extension based on the MIME type? Do we have other examples of OCR-D processors which determine a parameter value at runtime if no explicit value was given?

**Comment by kba** [comment]
> @kba, how should this issue be addressed? Do we require users to set the correct extension by using the `ext` parameter?
> 
> The `ext` parameter default is set in the JSON file. It is currently `.xml`, and I am afraid that automatic setting of the right parameter value would not fit to this default value. What about changing the default to an empty string and using that as an indicator to set the file extension based on the MIME type?

That's a good idea.

> Do we have other examples of OCR-D processors which determine a parameter value at runtime if no explicit value was given?

Yes, e.g. `gpu_id` in ocrd-anybaseocr-dewarp, which defaults to -1, which means to not use GPU at all. Also we do have the `MIME_TO_EXT` mapping in ocrd_utils and `ocrd bashlib constants`, so this wouldn't be hard to implement.

**Comment by kba** [comment]
Fixed in [v0.1.0](https://github.com/OCR-D/ocrd_fileformat/releases/v0.1.0).
