### ISSUE TITLE
Convert from ALTO-XML (V4.1) to PAGE-XML is failing

### ISSUE THREAD

**Issue by Shreeshrii** [OCR-D/ocrd_fileformat#23]
Since there seems to be a lot of interest in `fas` training, I decided to look at the data in [OpenITI/OCR_GS_Data](https://github.com/OpenITI/OCR_GS_Data/) to give it try with tesstrain. 

[OCR_GS_Data/TypeFaces/persian*](https://github.com/OpenITI/OCR_GS_Data/tree/master/TypeFaces) has png files and ALTO xml. These are v4.1. Since these did not work directly with `ocrd-segment-extract-lines`. I thought to convert them to PAGE format:

```
for i in ALTO/*; do base=$(basename "$i" .xml); ocrd workspace add "$i" -G ALTO -i "${base}_alto" -g "$base" -m application/alto+xml; done
for i in ALTO/*; do base=$(basename "$i" .xml); ocrd-fileformat-transform -P from-to "alto page" -I ALTO -O PAGE -g "$base" ; done
```
No PAGE files were generated, so I tried just for a single file. While "alto text" conversion is working, "alto page" is not.

```
(venv) (base) ubuntu@tesseract-ocr-1:~/fasGS$ ocrd-fileformat-transform -P from-to "alto page" -I ALTO -O PAGE -g ahsan_at_tavarikh_1
09:53:17.685 INFO ocrd-fileformat-transform - alto --> page: input file ahsan_at_tavarikh_1_alto (ahsan_at_tavarikh_1)
```
```
(venv) (base) ubuntu@tesseract-ocr-1:~/fasGS$  ocrd-fileformat-transform -P from-to "alto text" -I ALTO -O PAGE -g ahsan_at_tavarikh_1
09:54:53.183 INFO ocrd-fileformat-transform - alto --> text: input file ahsan_at_tavarikh_1_alto (ahsan_at_tavarikh_1)
09:55:00.625 INFO ocrd-fileformat-transform - Successfully executed: ocr-transform alto text ALTO/ahsan_at_tavarikh_1.xml PAGE/PAGE_0001.txt --
09:55:01.949 INFO ocrd.workspace.save_mets - Saving mets '/home/ubuntu/fasGS/mets.xml'
```

Is this the correct workflow to follow to split the ALTO page level info to lines?

**Comment by kba** [comment]
ocrd_fileformat is a wrapper for https://github.com/UB-Mannheim/ocr-fileformat which in turn delegates ALTO-PAGE transformation to https://github.com/PRImA-Research-Lab/prima-page-converter. When I run the PageConverter.jar directly on one of your sample images:

```sh
java -jar vendor/JPageConverter/PageConverter.jar -source-xml alto.xml -target-xml baz.xml
Could not save target PAGE XML file: baz.xml
java.lang.NullPointerException
        at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.writePage(PageXmlInputOutput.java:165)
        at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:256)
        at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:130)
```

I cannot debug this further because I cannot manage building PageConverter and the line numbers are inconsistent with the state in https://github.com/PRImA-Research-Lab/prima-core-libs. Perhaps @chris1010010 can spot the problem?

**Comment by kba** [comment]
But I can and will debug why the failed transformation registers as successful in ocr(d)_fileformat.

**Comment by kba** [comment]
I tried it with the latest JPageConverter and still get `NullPointerException`, albeit a different one:


```

**Comment by kba** [comment]
Correction, without the `-negCoords toZero` option in the cmdline, I still get

```
java.lang.NullPointerException
        at org.primaresearch.dla.page.io.xml.PageXmlInputOutput.writePage(PageXmlInputOutput.java:165)
        at org.primaresearch.dla.page.converter.PageConverter.run(PageConverter.java:316)
        at org.primaresearch.dla.page.converter.PageConverter.main(PageConverter.java:161)
```

Nothing more we can do, I'll open an issue upstream.

**Comment by kba** [comment]
Digging some more, I think I found the problem: The ALTO files you're trying to convert are not valid ALTO 4.1 but [an extension of ALTO 4.1](https://gitlab.inria.fr/scripta/escriptorium/-/raw/develop/app/escriptorium/static/alto-4-1-baselines.xsd) which changes the `BASELINE` attribute from an `xs:float` to a `PointsType`. So you will get errors like

```
cvc-datatype-valid.1.2.1: '686 600 759 594 883 590' is not a valid value for 'float'.
```

when validating against ALTO 4.1 XSD. 

If I remove all the baselines (`%s,BASELINE="[^"]*" ,,`) the ALTO is valid but the transformation still fails with the nondescript `Error writing target PAGE XML file`.

**Comment by kba** [comment]
Unfortunately, without upstream fix, there is nothing we can do here about it.
