### ISSUE TITLE
Release v0.1.2 missing?

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_fileformat#26]
Release v0.1.2 seems to be missing here on GitHub? The tag exists though.

![image](https://user-images.githubusercontent.com/34309482/106597130-42f6de80-6556-11eb-8c24-dd1d72c5194e.png)

**Comment by kba** [comment]
forgot to release on GH, fixed now: https://github.com/OCR-D/ocrd_fileformat/releases/tag/v0.1.2
