### ISSUE TITLE
When pip is not installed yet

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_fileformat#30]
(This issue is not super important to me, I just noticed this small inconvenience when testing ocrd_fileformat.)

Because I often use rather "blank" container images while testing I've encountered this line in the `Makefile`:

~~~
PIP ?= $(shell which pip)
~~~

When pip is not installed yet, this sets `$PIP` to nothing and the error message I get in line 37 (https://github.com/OCR-D/ocrd_fileformat/blob/master/Makefile#L37) is from the system's `install` (not from `pip install`!). This would yield a better error:

~~~
PIP ?= pip
~~~

I'm not sure if the `$(shell which pip)` construct has another purpose I'm not aware of. 

Side note: https://github.com/OCR-D/ocrd_fileformat/blob/master/Makefile#L90 doesn't use `$PIP`

**Comment by kba** [comment]
I don't know what that `PIP ?= $(shell which pip)` was about, we use `PIP ?= pip3` in other projects, so we should here as well.

**Comment by mikegerber** [comment]
> we use `PIP ?= pip3` in other projects, so we should here as well.

That also addresses the second problem: If I install `python3-pip` on an Ubuntu I still don't have `pip` but `pip3` 😀

**Comment by mikegerber** [comment]
I think this can be closed now, with cc6ae85 commited.
