### ISSUE TITLE
Offline use of PAGE → ALTO conversion

### ISSUE THREAD

**Issue by mikegerber** [OCR-D/ocrd_fileformat#32]
Currently converting from PAGE to ALTO - so one of the primary use cases for me - requires a working network connection and possibly a working HTTP proxy configuration to - apparently - load the ALTO schema. (#29) I also noticed that this conversion also needs to load - at least - `xlink.xsd` from the network.

There is code in PrimaDla.jar to load from a schema folder (`searchForAdditionalSchemas`), we should probably explore this first with the aim to pre-install all schemas in such a folder.

**Comment by mikegerber** [comment]
I think that code is only used in the unit tests, so we will have to patch prima-page-converter

**Comment by mikegerber** [comment]
Personally, I'm not super happy about relying on prima-page-converter for this. It's hard to work with (though that may be largely due to Java...), hard to build (https://github.com/PRImA-Research-Lab/prima-core-libs/issues/10) and one of the dependencies is closed source (https://github.com/PRImA-Research-Lab/prima-page-converter/issues/17).

Did someone explore the option of doing this conversion by other means, i.e. reimplementing it in Python?

**Comment by kba** [comment]
> Did someone explore the option of doing this conversion by other means, i.e. reimplementing it in Python?

Yes, I am going to invest a bit of time into this, since we need that conversion in many places and it must be fast and robust. I was going to first consider XSLT and if that turned out to be too cumbersome or inefficient, do the conversion in Python.

**Comment by mikegerber** [comment]
In addition to @kba's efforts at https://github.com/kba/page-to-alto, I also stumbled upon these XSLT files: https://gitlab.com/readcoop/transkribus/TranskribusCore/-/tree/master/src/main/resources/xslt

**Comment by mikegerber** [comment]
> In addition to @kba's efforts at https://github.com/kba/page-to-alto, I also stumbled upon these XSLT files: https://gitlab.com/readcoop/transkribus/TranskribusCore/-/tree/master/src/main/resources/xslt

At least `PageToAlto.xsl` does not contain any mention of `ReadingOrder` so I think it might me unsuitable.

**Comment by bertsky** [comment]
@mikegerber, did the Pythonic page-to-alto backend solve this for you?

**Comment by mikegerber** [comment]
> @mikegerber, did the Pythonic page-to-alto backend solve this for you?

Yes!
