### ISSUE TITLE
pass script-args

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_fileformat#4]
Currently, the `script-args` param does not get passed over to `ocr-transform`. IIUC, this should be used for the Saxon parameters in the [last position](https://github.com/OCR-D/ocrd_fileformat/blob/de5b53282243c0b9696bf1ca9a22c327793ef37d/ocrd-fileformat-transform#L87).

**Comment by M3ssman** [comment]
What's the problem so far? 
I integrated the step into a Makefile-configuration, with parameters and it converted PAGE to ALTO (V4).
Looks like it's working. 
Good job!

**Comment by bertsky** [comment]
The issue is not with the base functionality, but with the [script-args](https://github.com/OCR-D/ocrd_fileformat/blob/de5b53282243c0b9696bf1ca9a22c327793ef37d/ocrd-tool.json#L52) parameter which does not get passed to the backend. So when you want/need to pass options to Saxon, they get ignored.
