### ISSUE TITLE
does not work with nondefault METS basename

### ISSUE THREAD

**Issue by bertsky** [OCR-D/ocrd_fileformat#40]
When running on a workspace with URL ending in anything but `mets.xml`, the input gets processed, but the METS is not updated.

The reason seems to be that the final `ocrd workspace bulk-add` command should use `ocrd workspace -m ${ocrd__argv[mets]} bulk-add` (but after we chdired we should strip the directory part).

**Comment by bertsky** [comment]
@kba I'm afraid this apply to all of our bashlib processors…

**Comment by kba** [comment]
> @kba I'm afraid this apply to all of our bashlib processors…

Indeed, it does, cf. https://github.com/OCR-D/core/issues/927
